server:
  port: 8080
  address: 0.0.0.0

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/user/**

        - id: auth-auth
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

        - id: restaurant-service
          uri: http://restaurant-service:8080
          predicates:
            - Path=/restaurant/**
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/shopping-cart/**, /order/**
        - id: notification-service
          uri: http://notification-service:8080
          predicates:
            - Path=/ws/**
